name: Run Locust Tests on Commit

on:
  push:
    branches:
      - main

jobs:
  locust-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le dépôt
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Démarrer le serveur Flask
      - name: Start Flask server
        run: |
          python server.py &
          echo "Waiting for Flask server to start"
          sleep 30

